BUCKET_NAME = "nxs"
LOCAL_FILE_PATH = "C:\\Users\\vinic\\OneDrive\\Área de Trabalho\\nexus\\arquivos"
GCS_SUBFOLDER = "gs://nxs/csv_files"
GCS_SUBFOLDER_TEMPLATE = "gs://nxs/templates/"
STAGING_LOCATION = "gs://nxs/temp"
TEMP_LOCATION = "gs://nxs/templates/"
